name: Publish Docker Images (Public)

on:
  workflow_call:
    inputs:
      remote-repository:
        description: 'Name of the GCP managed Artifact Registry.'
        default: "us-central1-docker.pkg.dev/topl-shared-project-dev/topl-artifacts-dev/"
        required: false
        type: string
      registry-auth-location:
        description: 'Name of the GCP managed Artifact Registry.'
        default: "us-central1-docker.pkg.dev"
        required: false
        type: string
      remote-docker-image:
        description: 'Remote Docker image. ex: toplprotocol/annulus'
        default: "toplprotocol/annulus"
        required: false
        type: string

jobs:
  publish_docker_images:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ inputs.remote-docker-image }}

      - name: Echo metadata
        run: |
          echo "tags: ${{ steps.meta.outputs.tags }}"
          echo "labels: ${{ steps.meta.outputs.labels }}"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
