name: PR
on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/_build.yml

  flutter_test:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          cache: true
      - name: Install dependencies and generate files
        run: make gen
      - name: Run tests
        run: flutter test --dart-define=FLUTTER_TEST=true
