# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image (Unofficial)

on:
  push:
    branches:
      - main
      - dev
      - BN-1013-prerequisite-annulus-ci-cd-docker

jobs:
  build:
    uses: ./.github/workflows/_build.yml 

  publish_private:
    uses: ./.github/workflows/_docker_publish_private.yml
    needs: [build]
    secrets: inherit
    with:
      remote-docker-image: "us-central1-docker.pkg.dev/topl-shared-project-dev/topl-artifacts-dev/annulus"
